app:
  name: 'user'
  version: '1.0.0'
  token_expire: 86400
  secret: 'howareyoutoday'

logger:
  log_level: 'debug'
  # rollbar_env: 'go-clean-template'

consul:  
  check_api: '/user/healthz'
  # consul心跳间隔, 秒
  interval: '3'
  # 心跳超时, 秒
  timeout: '3'
  tags: ['urlprefix-/user strip=/user']


postgres:
  pool_max: 2
  url: 'postgresql://dev_user:dev123@dog.ap:5432/user'

wx:
  appid: ''
  appsecret: ''
